name: CoderCo CICD workflow 

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v2
      - name: we are testing this workflow
        run: echo hello everyone! 


    



